### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by puranjayjain** [alohaas/language-nunjucks#13]
I am able to see a couple of prs pending and one not merged.
Can someone tell me if this repo is abandoned or still maintained? 
I'll be happy to take over as a maintainer if the original creator has time bound issues.

**Comment by alohaas** [comment]
Hey @puranjayjain the repo is not abandoned. I will be addressing the pull requests in question. 
I would advise that in the future, you @ mention the repo maintainer when addressing them directly to receive a quicker response. That goes for any collaborators involved as well.

**Comment by puranjayjain** [comment]
@alohaas sorry I thought you had the notifications on my bad :smile:
