### ISSUE TITLE
formatting not working in 1.9.9

### ISSUE THREAD

**Issue by pete-hotchkiss** [alohaas/language-nunjucks#19]
Cant account for previous versions, but currently no files with .nunj extension are picking up formatting.

**Comment by puranjayjain** [comment]
@pete-hotchkiss the recognised formats are .njk , .nunjucks or .html. You should stick to .njk as it is the defacto-standard for nunjucks.

**Comment by alohaas** [comment]
@pete-hotchkiss, as @puranjayjain explained above, we are following the convention suggested in the [docs](https://mozilla.github.io/nunjucks/templating.html). Closing this issue.
