### ISSUE TITLE
how to config to run in the file which is not '.nunjucks' file

### ISSUE THREAD

**Issue by atmjs** [alohaas/language-nunjucks#20]
how to config to run in the file which is not '.nunjucks' file?
for example , I want to use 'test.html' but not 'test.nunjucks'

**Comment by puranjayjain** [comment]
Change the language from the bottom of the atom  editor to nunjucks manually

**Comment by atmjs** [comment]
@puranjayjain thanks!

**Comment by alohaas** [comment]
Thanks @puranjayjain. Closing this issue.
