### ISSUE TITLE
Problem With Autocomplete for "else"

### ISSUE THREAD

**Issue by Gchesta** [alohaas/language-nunjucks#24]
Nunjucks syntax for conditional flow of if and else is: `{% if condition%} {% else %}` . However, the autocomplete is prompting . `{% if condition%} {% else condition %}`

**Comment by revelt** [comment]
@Gchesta please check again and confirm this is an issue because I can't recreate it:

![if-else](https://user-images.githubusercontent.com/8344688/31542543-5c0ddfd6-b00a-11e7-8c2e-7ec72292097c.gif)

**Comment by frasertmay** [comment]
I cannot replicate this either so I'm going to close the issue

**Comment by revelt** [comment]
it must have been a glitch or something
