### ISSUE TITLE
Failed

### ISSUE THREAD

**Issue by onepiece92** [alohaas/language-nunjucks#26]
,nothin happens .. nunjuck codes are still pale white and no auto complete . is there something that override nunjucks

**Comment by puranjayjain** [comment]
@onepiece92 can you provide more details like what file extensions, a screenshot if possible

**Comment by onepiece92** [comment]
Sorry for the trouble ... i missed the scope extension - this is a great plugin .. thank you for your kind help. 
adding .html.nunjucks worked just fine now.
