### ISSUE TITLE
if the file has a - in filename nunjucks language is not being detected

### ISSUE THREAD

**Issue by jinmatt** [alohaas/language-nunjucks#8]

**Comment by alohaas** [comment]
Hey @jinmatt thanks for opening the issue. Are you referring to an instance like this:

`{% extends "header-base.html" %}`

**Comment by jinmatt** [comment]
@alohaas yes

**Comment by alohaas** [comment]
@jinmatt apologies for the delay. Working on some updates today.

**Comment by matheusdarosa** [comment]
Hey @alohaas, is this bug still on your roadmap? :)

**Comment by revelt** [comment]
Can somebody confirm, is this issue still happening?

Currently I'm using Atom and this plugin (v4.1.0) and my files do have hyphens in their names, for example, `macro-footers-content.nunjucks` — I don't see any issues with Nunjucks being recognised:

![nujucks](https://cloud.githubusercontent.com/assets/8344688/24710857/453c01e6-1a16-11e7-8338-dc9701dada29.png)

**Comment by alohaas** [comment]
@matheusdarosa  @jinmatt this has been fixed. I neglected to close this issue after updating to v 4.1.0 You should be seeing something similar to ...
![screen shot 2017-04-14 at 3 12 28 pm](https://cloud.githubusercontent.com/assets/4480279/25053369/e11099d2-2124-11e7-9032-e05163e5a6b9.png)

Please reopen this issue if it persists, but I'm closing it now.
